name: Build All Apps

on:
  release:
    types: [created]
    tags:
      - 'v*'
      - 'dev*'
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12
  FLUTTER_VERSION: 3.27.4

jobs:
  # build-linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Setup Python ${{ env.PYTHON_VERSION }}
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: ${{ env.PYTHON_VERSION }}

  #   - name: Install Python Dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt

  #   - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: ${{ env.FLUTTER_VERSION }}

  #   - name: Patch for linux build
  #     run: |
  #       flutter doctor
  #       sudo apt-get update -y
  #       sudo apt-get install -y ninja-build libgtk-3-dev
  #       flutter doctor

  #   - name: Flet Build Linux
  #     run: |
  #       flutter config --no-analytics 
  #       flet build linux --no-rich-output

  #   - name: Package Linux Build
  #     run: |
  #       cd build
  #       zip -r linux-build.zip linux/
  #       cd ..

  #   - name: Upload to Release
  #     if: startsWith(github.ref, 'refs/tags/')
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       files: build/linux-build.zip
  #       

  # build-macos:
  #   runs-on: macos-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Setup Python ${{ env.PYTHON_VERSION }}
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: ${{ env.PYTHON_VERSION }}

  #   - name: Install Python Dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt

  #   - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: ${{ env.FLUTTER_VERSION }}

  #   - name: Flet Build macOS
  #     run: |
  #       flutter config --no-analytics
  #       flet build macos --verbose --no-rich-output

  #   - name: Package macOS Build
  #     run: |
  #       cd build
  #       zip -r macos-build.zip macos/
  #       cd ..

  #   - name: Upload to Release
  #     if: startsWith(github.ref, 'refs/tags/')
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       files: build/macos-build.zip
  #       

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Flet Build Windows
      env:
        FLET_CLI_NO_RICH_OUTPUT: "True"
      run: |
        flet build windows
    - name: Package Windows Build
      run: |
        Compress-Archive -Path build/windows -DestinationPath build/windows-build.zip

    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/windows-build.zip
        

  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Flet Build APK
      run: |
        flet build apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/apk
        if-no-files-found: warn
        overwrite: false

    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/apk/**/*


  # build-ipa:
  #   runs-on: macos-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Setup Python ${{ env.PYTHON_VERSION }}
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: ${{ env.PYTHON_VERSION }}

  #   - name: Install Python Dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt

  #   - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: ${{ env.FLUTTER_VERSION }}

  #   - name: Flet Build IPA
  #     run: |
  #       flutter config --no-analytics
  #       flet build ipa --verbose --no-rich-output

  #   - name: Upload IPA Artifact
  #     uses: actions/upload-artifact@v4.3.4
  #     with:
  #       name: ipa-build-artifact
  #       path: build/ipa
  #       if-no-files-found: warn
  #       overwrite: false

  #   - name: Upload to Release
  #     if: startsWith(github.ref, 'refs/tags/')
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       files: build/ipa/**/*
  #       