name: Build iOS App

on:
  release:
    types: [created]
    tags:
      - 'v*'
      - 'dev*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install iOS platform
      run: |
        xcodebuild -downloadPlatform iOS
        
    - name: Build iOS App
      run: |
        pip install -r requirements.txt
        flet build ipa
        echo "Listing build/ipa directory contents:"
        ls -la build/ipa
        echo "Listing build/ipa/Runner.xcarchive contents:"
        ls -la build/ipa/Runner.xcarchive
        # 尝试查找实际的 ipa 文件
        find build -name "*.ipa" -type f
        # 如果找到 ipa 文件，则移动它
        if [ -f build/ipa/Runner.xcarchive/Products/Applications/Runner.ipa ]; then
          mv build/ipa/Runner.xcarchive/Products/Applications/Runner.ipa app-release.ipa
        else
          echo "Error: Could not find the IPA file"
          exit 1
        fi
        
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-ios
        path: app-release.ipa
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: app-release.ipa
        generate_release_notes: true 