name: Build iOS App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install iOS platform
      run: |
        xcodebuild -downloadPlatform iOS
        
    - name: Build iOS App
      run: |
        pip install -r requirements.txt
        flet build ipa
        mv build/ipa/app.ipa app-release.ipa
        
    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-ios
        path: app-release.ipa
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: app-release.ipa
        generate_release_notes: true 